const InfoPersonajes = [
    {
        id      : 1,
        nombre  : 'Arthur Pendragon',
        clase   : 'Espada / Saber',
        origen  : 'Gran Bretaña',
        imagen  : '../assets/saber.png',
        maestro : 'Shirou Emiya',
        css     : 'saber',
    },
    {
        id      : 2,
        nombre  : 'Shirou Emiya',
        clase   : 'Arquero / Archer',
        origen  : 'Japón',
        imagen  : '../assets/Archer.png',
        maestro : 'Rin Tohsaka',
        css     : 'archer',
    },
    {
        id      : 3,
        nombre  : 'Medusa',
        clase   : 'Jinete / Rider',
        origen  : 'Grecia',
        imagen  : '../assets/Rider.png',
        maestro : 'Shinji Matou',
        css     : 'rider',
    },
    {
        id      : 4,
        nombre  : 'Cú Chulainn',
        clase   : 'Lanza / Lancer',
        origen  : 'Irlanda',
        imagen  : '../assets/Lancer.png',
        maestro : 'Kirei Kotomine',
        css     : 'lancer',
    },
    {
        id      : 5,
        nombre  : 'Hercules',
        clase   : 'Berserker',
        origen  : 'Grecia',
        imagen  : '../assets/Berserker.png',
        maestro : 'Illyasviel von Einzbern',
        css     : 'berserker',
    },
    {
        id      : 6,
        nombre  : 'Medea',
        clase   : 'Hechicero / Caster',
        origen  : 'Grecia',
        imagen  : '../assets/Caster.png',
        maestro : 'Souichirou Kuzuki',
        css     : 'caster',
    },
    {
        id      : 7,
        nombre  : 'Sasaki Kojirou',
        clase   : 'Assassin / Asesino',
        origen  : 'Japón',
        imagen  : '../assets/Assassin.png',
        maestro : 'Caster',
        css     : 'assassin',
    },
]